version: '3.3'
services:
  web:
    build:
      context: .
    restart: always
    environment: 
      - WEB_CONCURRENCY=6
    volumes:
      - /data/ytdl_embed:/app/cache
    networks:
      - t2_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=t2_proxy"
      ## HTTP Routers
      - "traefik.http.routers.embed-rtr.entrypoints=https"
      - "traefik.http.routers.embed-rtr.rule=Host(`embed.yadamiel.com`)"
      - "traefik.http.routers.embed-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.embed-rtr.middlewares=chain-no-auth@file"
      ## HTTP Services
      - "traefik.http.routers.embed-rtr.service=embed-svc"
      - "traefik.http.services.embed-svc.loadbalancer.server.port=80"


  fileserve:
    restart: always
    image: flashspys/nginx-static
    volumes: 
      - /data/ytdl_embed:/static/mp4
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - t2_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=t2_proxy"
      ## HTTP Routers
      - "traefik.http.routers.static_embed-rtr.entrypoints=https"
      - "traefik.http.routers.static_embed-rtr.rule=Host(`embed.yadamiel.com`) && PathPrefix(`/mp4`)"
      - "traefik.http.routers.static_embed-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.static_embed-rtr.middlewares=chain-no-auth@file"
      ## HTTP Services
      - "traefik.http.routers.static_embed-rtr.service=static_embed-svc"
      - "traefik.http.services.static_embed-svc.loadbalancer.server.port=80"

networks:
  t2_proxy:
    external:
      name: t2_proxy